name: solana_kit
description: Umbrella package re-exporting all Solana Kit Dart SDK packages.
version: 0.0.2
repository: https://github.com/openbudgetfun/solana_kit

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_accounts:
  solana_kit_addresses:
  solana_kit_codecs:
  solana_kit_errors:
  solana_kit_fast_stable_stringify:
  solana_kit_functional:
  solana_kit_instruction_plans:
  solana_kit_instructions:
  solana_kit_keys:
  solana_kit_offchain_messages:
  solana_kit_options:
  solana_kit_program_client_core:
  solana_kit_programs:
  solana_kit_rpc:
  solana_kit_rpc_parsed_types:
  solana_kit_rpc_spec_types:
  solana_kit_rpc_subscriptions:
  solana_kit_rpc_transport_http:
  solana_kit_rpc_types:
  solana_kit_signers:
  solana_kit_subscribable:
  solana_kit_sysvars:
  solana_kit_transaction_confirmation:
  solana_kit_transaction_messages:
  solana_kit_transactions:

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
