name: solana_kit_addresses
description: Base58 address utilities for the Solana Kit Dart SDK.
version: 0.0.1

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  crypto: ^3.0.6
  solana_kit_codecs_core:
  solana_kit_codecs_strings:
  solana_kit_errors:

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
