name: solana_kit_instruction_plans
description: Instruction planning for the Solana Kit Dart SDK.
version: 0.0.2

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_errors:
  solana_kit_instructions:
  solana_kit_keys:
  solana_kit_transaction_messages:
  solana_kit_transactions:

dev_dependencies:
  solana_kit_addresses:
  solana_kit_lints:
  test: ^1.25.8
