[github]
owner = "openbudgetfun"
repo = "solana_kit"

[changes]
ignore_conventional_commits = true

###############################################################################
# Packages
###############################################################################

[packages.solana_kit]
versioned_files = ["packages/solana_kit/pubspec.yaml"]
scopes = ["solana_kit"]
changelog = "packages/solana_kit/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_accounts]
versioned_files = ["packages/solana_kit_accounts/pubspec.yaml"]
scopes = ["solana_kit_accounts"]
changelog = "packages/solana_kit_accounts/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_addresses]
versioned_files = ["packages/solana_kit_addresses/pubspec.yaml"]
scopes = ["solana_kit_addresses"]
changelog = "packages/solana_kit_addresses/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_codecs]
versioned_files = ["packages/solana_kit_codecs/pubspec.yaml"]
scopes = ["solana_kit_codecs"]
changelog = "packages/solana_kit_codecs/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_codecs_core]
versioned_files = ["packages/solana_kit_codecs_core/pubspec.yaml"]
scopes = ["solana_kit_codecs_core"]
changelog = "packages/solana_kit_codecs_core/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_codecs_data_structures]
versioned_files = ["packages/solana_kit_codecs_data_structures/pubspec.yaml"]
scopes = ["solana_kit_codecs_data_structures"]
changelog = "packages/solana_kit_codecs_data_structures/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_codecs_numbers]
versioned_files = ["packages/solana_kit_codecs_numbers/pubspec.yaml"]
scopes = ["solana_kit_codecs_numbers"]
changelog = "packages/solana_kit_codecs_numbers/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_codecs_strings]
versioned_files = ["packages/solana_kit_codecs_strings/pubspec.yaml"]
scopes = ["solana_kit_codecs_strings"]
changelog = "packages/solana_kit_codecs_strings/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_errors]
versioned_files = ["packages/solana_kit_errors/pubspec.yaml"]
scopes = ["solana_kit_errors"]
changelog = "packages/solana_kit_errors/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_fast_stable_stringify]
versioned_files = ["packages/solana_kit_fast_stable_stringify/pubspec.yaml"]
scopes = ["solana_kit_fast_stable_stringify"]
changelog = "packages/solana_kit_fast_stable_stringify/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_functional]
versioned_files = ["packages/solana_kit_functional/pubspec.yaml"]
scopes = ["solana_kit_functional"]
changelog = "packages/solana_kit_functional/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_helius]
versioned_files = ["packages/solana_kit_helius/pubspec.yaml"]
scopes = ["solana_kit_helius"]
changelog = "packages/solana_kit_helius/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_instruction_plans]
versioned_files = ["packages/solana_kit_instruction_plans/pubspec.yaml"]
scopes = ["solana_kit_instruction_plans"]
changelog = "packages/solana_kit_instruction_plans/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_instructions]
versioned_files = ["packages/solana_kit_instructions/pubspec.yaml"]
scopes = ["solana_kit_instructions"]
changelog = "packages/solana_kit_instructions/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_keys]
versioned_files = ["packages/solana_kit_keys/pubspec.yaml"]
scopes = ["solana_kit_keys"]
changelog = "packages/solana_kit_keys/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_lints]
versioned_files = ["packages/solana_kit_lints/pubspec.yaml"]
scopes = ["solana_kit_lints"]
changelog = "packages/solana_kit_lints/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_mobile_wallet_adapter]
versioned_files = ["packages/solana_kit_mobile_wallet_adapter/pubspec.yaml"]
scopes = ["solana_kit_mobile_wallet_adapter"]
changelog = "packages/solana_kit_mobile_wallet_adapter/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_mobile_wallet_adapter_protocol]
versioned_files = ["packages/solana_kit_mobile_wallet_adapter_protocol/pubspec.yaml"]
scopes = ["solana_kit_mobile_wallet_adapter_protocol"]
changelog = "packages/solana_kit_mobile_wallet_adapter_protocol/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_offchain_messages]
versioned_files = ["packages/solana_kit_offchain_messages/pubspec.yaml"]
scopes = ["solana_kit_offchain_messages"]
changelog = "packages/solana_kit_offchain_messages/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_options]
versioned_files = ["packages/solana_kit_options/pubspec.yaml"]
scopes = ["solana_kit_options"]
changelog = "packages/solana_kit_options/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_program_client_core]
versioned_files = ["packages/solana_kit_program_client_core/pubspec.yaml"]
scopes = ["solana_kit_program_client_core"]
changelog = "packages/solana_kit_program_client_core/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_programs]
versioned_files = ["packages/solana_kit_programs/pubspec.yaml"]
scopes = ["solana_kit_programs"]
changelog = "packages/solana_kit_programs/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc]
versioned_files = ["packages/solana_kit_rpc/pubspec.yaml"]
scopes = ["solana_kit_rpc"]
changelog = "packages/solana_kit_rpc/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_api]
versioned_files = ["packages/solana_kit_rpc_api/pubspec.yaml"]
scopes = ["solana_kit_rpc_api"]
changelog = "packages/solana_kit_rpc_api/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_parsed_types]
versioned_files = ["packages/solana_kit_rpc_parsed_types/pubspec.yaml"]
scopes = ["solana_kit_rpc_parsed_types"]
changelog = "packages/solana_kit_rpc_parsed_types/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_spec]
versioned_files = ["packages/solana_kit_rpc_spec/pubspec.yaml"]
scopes = ["solana_kit_rpc_spec"]
changelog = "packages/solana_kit_rpc_spec/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_spec_types]
versioned_files = ["packages/solana_kit_rpc_spec_types/pubspec.yaml"]
scopes = ["solana_kit_rpc_spec_types"]
changelog = "packages/solana_kit_rpc_spec_types/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_subscriptions]
versioned_files = ["packages/solana_kit_rpc_subscriptions/pubspec.yaml"]
scopes = ["solana_kit_rpc_subscriptions"]
changelog = "packages/solana_kit_rpc_subscriptions/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_subscriptions_api]
versioned_files = ["packages/solana_kit_rpc_subscriptions_api/pubspec.yaml"]
scopes = ["solana_kit_rpc_subscriptions_api"]
changelog = "packages/solana_kit_rpc_subscriptions_api/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_subscriptions_channel_websocket]
versioned_files = ["packages/solana_kit_rpc_subscriptions_channel_websocket/pubspec.yaml"]
scopes = ["solana_kit_rpc_subscriptions_channel_websocket"]
changelog = "packages/solana_kit_rpc_subscriptions_channel_websocket/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_transport_http]
versioned_files = ["packages/solana_kit_rpc_transport_http/pubspec.yaml"]
scopes = ["solana_kit_rpc_transport_http"]
changelog = "packages/solana_kit_rpc_transport_http/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_transformers]
versioned_files = ["packages/solana_kit_rpc_transformers/pubspec.yaml"]
scopes = ["solana_kit_rpc_transformers"]
changelog = "packages/solana_kit_rpc_transformers/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_rpc_types]
versioned_files = ["packages/solana_kit_rpc_types/pubspec.yaml"]
scopes = ["solana_kit_rpc_types"]
changelog = "packages/solana_kit_rpc_types/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_signers]
versioned_files = ["packages/solana_kit_signers/pubspec.yaml"]
scopes = ["solana_kit_signers"]
changelog = "packages/solana_kit_signers/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_subscribable]
versioned_files = ["packages/solana_kit_subscribable/pubspec.yaml"]
scopes = ["solana_kit_subscribable"]
changelog = "packages/solana_kit_subscribable/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_sysvars]
versioned_files = ["packages/solana_kit_sysvars/pubspec.yaml"]
scopes = ["solana_kit_sysvars"]
changelog = "packages/solana_kit_sysvars/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_test_matchers]
versioned_files = ["packages/solana_kit_test_matchers/pubspec.yaml"]
scopes = ["solana_kit_test_matchers"]
changelog = "packages/solana_kit_test_matchers/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_transaction_confirmation]
versioned_files = ["packages/solana_kit_transaction_confirmation/pubspec.yaml"]
scopes = ["solana_kit_transaction_confirmation"]
changelog = "packages/solana_kit_transaction_confirmation/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_transaction_messages]
versioned_files = ["packages/solana_kit_transaction_messages/pubspec.yaml"]
scopes = ["solana_kit_transaction_messages"]
changelog = "packages/solana_kit_transaction_messages/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

[packages.solana_kit_transactions]
versioned_files = ["packages/solana_kit_transactions/pubspec.yaml"]
scopes = ["solana_kit_transactions"]
changelog = "packages/solana_kit_transactions/CHANGELOG.md"
extra_changelog_sections = [
  { name = "Notes", types = ["note"] },
  { name = "Documentation", types = ["docs"] },
]

# Workflows

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows.steps]]
type = "Command"
command = "dprint fmt --config dprint.json"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "dprint fmt --config dprint.json"

[[workflows.steps]]
type = "Command"
command = "git add --all"

[[workflows.steps]]
type = "Command"
command = "git commit -m 'chore: prepare release'"

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "forced-release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "publish"

[[workflows.steps]]
type = "Command"
command = "melos publish --no-private --no-dry-run"
