name: solana_kit_signers
description: Signer interfaces for the Solana Kit Dart SDK.
version: 0.0.1

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_errors:
  solana_kit_keys:

dev_dependencies:
  solana_kit_lints:
