name: solana_kit_rpc_subscriptions_api
description: Subscription method definitions for the Solana Kit Dart SDK.
version: 0.0.1

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_addresses:
  solana_kit_errors:
  solana_kit_keys:
  solana_kit_rpc_types:

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.8
