name: solana_kit_keys
description: Key pair and Ed25519 operations for the Solana Kit Dart SDK.
version: 0.0.1

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  ed25519_edwards: ^0.3.1
  solana_kit_addresses:
  solana_kit_codecs_core:
  solana_kit_codecs_strings:
  solana_kit_errors:

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
