name: solana_kit_rpc_subscriptions
description: Subscription client for the Solana Kit Dart SDK.
version: 0.1.0
repository: https://github.com/openbudgetfun/solana_kit

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_errors: ^0.1.0
  solana_kit_fast_stable_stringify: ^0.1.0
  solana_kit_rpc_spec_types: ^0.1.0
  solana_kit_rpc_subscriptions_api: ^0.1.0
  solana_kit_rpc_subscriptions_channel_websocket: ^0.1.0
  solana_kit_rpc_types: ^0.1.0
  solana_kit_subscribable: ^0.1.0

dev_dependencies:
  fake_async: ^1.3.3
  solana_kit_lints: ^0.1.0
  test: ^1.25.8
