name: solana_kit_rpc_subscriptions
description: Subscription client for the Solana Kit Dart SDK.
version: 0.0.2

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_errors:
  solana_kit_fast_stable_stringify:
  solana_kit_rpc_spec_types:
  solana_kit_rpc_subscriptions_api:
  solana_kit_rpc_subscriptions_channel_websocket:
  solana_kit_rpc_types:
  solana_kit_subscribable:

dev_dependencies:
  fake_async: ^1.3.3
  solana_kit_lints:
  test: ^1.25.8
