name: solana_kit_rpc_subscriptions_channel_websocket
description: WebSocket channel for RPC subscriptions for the Solana Kit Dart SDK.
version: 0.0.2
repository: https://github.com/openbudgetfun/solana_kit

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_errors:
  solana_kit_subscribable:
  web_socket_channel: ^3.0.2

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.8
