name: solana_kit_codecs
description: Umbrella package re-exporting all codec sub-packages for the Solana Kit Dart SDK.
version: 0.0.1

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_codecs_core:
  solana_kit_codecs_data_structures:
  solana_kit_codecs_numbers:
  solana_kit_codecs_strings:

dev_dependencies:
  solana_kit_lints:
