name: solana_kit_offchain_messages
description: Off-chain message signing for the Solana Kit Dart SDK.
version: 0.0.2
repository: https://github.com/openbudgetfun/solana_kit

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  meta: ^1.16.0
  solana_kit_addresses:
  solana_kit_codecs_core:
  solana_kit_codecs_data_structures:
  solana_kit_codecs_numbers:
  solana_kit_codecs_strings:
  solana_kit_errors:
  solana_kit_keys:

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
