name: solana_kit_functional
description: Pipe and compose utilities for the Solana Kit Dart SDK.
version: 0.0.2

environment:
  sdk: ^3.10.1

resolution: workspace

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
