name: solana_kit_codecs_numbers
description: Numeric codecs for the Solana Kit Dart SDK.
version: 0.0.2

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_codecs_core:
  solana_kit_errors:

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
