name: solana_kit_accounts
description: Account fetching and decoding for the Solana Kit Dart SDK.
version: 0.0.2

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  meta: ^1.16.0
  solana_kit_addresses:
  solana_kit_codecs_core:
  solana_kit_codecs_strings:
  solana_kit_errors:
  solana_kit_rpc_spec:
  solana_kit_rpc_types:

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
