name: solana_kit_rpc_transport_http
description: HTTP transport for the Solana Kit Dart SDK.
version: 0.0.1

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_errors:
  solana_kit_rpc_spec:

dev_dependencies:
  solana_kit_lints:
