name: solana_kit_rpc_transport_http
description: HTTP transport for the Solana Kit Dart SDK.
version: 0.0.2

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  http: ^1.4.0
  solana_kit_errors:
  solana_kit_rpc_spec:
  solana_kit_rpc_spec_types:

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
