name: solana_kit_sysvars
description: System variable access for the Solana Kit Dart SDK.
version: 0.0.2

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  meta:
  solana_kit_accounts:
  solana_kit_addresses:
  solana_kit_codecs_core:
  solana_kit_codecs_data_structures:
  solana_kit_codecs_numbers:
  solana_kit_errors:
  solana_kit_rpc_spec:
  solana_kit_rpc_types:

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
