name: solana_kit_codecs_data_structures
description: Struct, enum, tuple, and map codecs for the Solana Kit Dart SDK.
version: 0.0.1

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_codecs_core:
  solana_kit_codecs_numbers:
  solana_kit_errors:

dev_dependencies:
  solana_kit_lints:
