name: solana_kit_errors
description: Error codes and SolanaError class for the Solana Kit Dart SDK.
version: 0.0.1

environment:
  sdk: ^3.10.1

resolution: workspace

dev_dependencies:
  solana_kit_lints:
  test: ^1.25.0
