name: solana_kit_rpc
description: Primary RPC client for the Solana Kit Dart SDK.
version: 0.0.1

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_errors:
  solana_kit_rpc_api:
  solana_kit_rpc_spec:
  solana_kit_rpc_transformers:
  solana_kit_rpc_transport_http:
  solana_kit_rpc_types:

dev_dependencies:
  solana_kit_lints:
