name: solana_kit_rpc
description: Primary RPC client for the Solana Kit Dart SDK.
version: 0.1.0
repository: https://github.com/openbudgetfun/solana_kit

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  http: ^1.4.0
  solana_kit_errors: ^0.1.0
  solana_kit_fast_stable_stringify: ^0.1.0
  solana_kit_rpc_api: ^0.1.0
  solana_kit_rpc_spec: ^0.1.0
  solana_kit_rpc_spec_types: ^0.1.0
  solana_kit_rpc_transformers: ^0.1.0
  solana_kit_rpc_transport_http: ^0.1.0
  solana_kit_rpc_types: ^0.1.0

dev_dependencies:
  solana_kit_lints: ^0.1.0
  test: ^1.25.0
