name: solana_kit_rpc_transformers
description: Request and response transformers for the Solana Kit Dart SDK.
version: 0.0.2
repository: https://github.com/openbudgetfun/solana_kit

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_errors:
  solana_kit_rpc_spec_types:
  solana_kit_rpc_types:

dev_dependencies:
  solana_kit_lints:
  test:
