name: solana_kit_program_client_core
description: Program client core for the Solana Kit Dart SDK.
version: 0.1.0
repository: https://github.com/openbudgetfun/solana_kit

environment:
  sdk: ^3.10.1

resolution: workspace

dependencies:
  solana_kit_accounts: ^0.1.0
  solana_kit_addresses: ^0.1.0
  solana_kit_codecs_core: ^0.1.0
  solana_kit_errors: ^0.1.0
  solana_kit_instructions: ^0.1.0
  solana_kit_rpc_spec: ^0.1.0
  solana_kit_rpc_types: ^0.1.0
  solana_kit_signers: ^0.1.0

dev_dependencies:
  solana_kit_keys: ^0.1.0
  solana_kit_lints: ^0.1.0
  solana_kit_transactions: ^0.1.0
  test: ^1.25.0
